### ISSUE TITLE
difference between kovan and rinkeby

### ISSUE THREAD

**Issue by come-maiz** [ethereumbook/ethereumbook#198]
On the intro.asciidoc, on the metamask section, the testnets are presented. But, the text explaining Kovan is the same as the one explaining Rinkeby:

>Kovan Test Network:: Ethereum public test blockchain and network, using Proof-of-Authority consensus (federated signing). ETH on this network has no value.

>Rinkeby Test Network:: Ethereum public test blockchain and network, using Proof-of-Authority consensus (federated signing). ETH on this network has no value.

This brings the question about why do we have two, instead of just one. So I think the text should be expanded a little, to include the difference between the two.

**Comment by wbnns** [comment]
@elopio Thanks for the suggestion. Would you be interested in submitting a pull request to expand the text?

**Comment by come-maiz** [comment]
@wbnns, I would love too, but I'm learning with this book😃 I don't yet know the difference.

**Comment by AyushyaChitransh** [comment]
I can say about one difference which I know:

 - Kovan uses aura consensus mechanism(aka authority round) while rinkeby uses clique algorithm.
 - Kovan genesis can be found [here](https://github.com/paritytech/parity/blob/master/ethcore/res/ethereum/kovan.json) and rinkeby genesis can be found [here](https://github.com/ethereum/go-ethereum/blob/55599ee95d4151a2502465e0afc7c47bd1acba77/core/genesis.go#L336)

**Comment by AyushyaChitransh** [comment]
As I was collecting information about networks, I found that this can be more detailed. There are public networks like:

 - Mainnet: Main ethereum network, it has real ether and real value. Currently this network is known as ETH.
 - Classic: Ethereum Classic network. The mainnet which did not support hard fork after DAO hack. Currently this network is known as ETC. This also has real ether and has real value. This is supported by lesser number of peoples in blockchain world, because most supported hard fork and therefore switched to new network.
 - Morden testnet: Ethereum's first official testnet
 - Ropsten: POW based network. The issue with Ropsten was that the attacker minted tens of thousands of blocks, producing huge reorgs and pushing the gas limit up to 9B.
 - Rinkeby: The POA based test network. The popular one and currently being used. Parity cannot connect to this network since it has not implemented Clique consensus mechanism. Its plan to support it have been superseded by a new upcoming network as indicated [here](https://github.com/paritytech/parity/issues/5687).
 - Kovan: The POA test network using `Aura` consensus mechanism, also known as Authority round. Geth cannot connect to this network, as it does not implement this consensus mechanism.

We might require more details in order to go deep into the differences of networks and advantage of one network over another.

## Networks

After these public networks comes the broader scene of networks and their types. They can be classified on basis of the consensus mechanism they use

 - POW: Proof of work
 - POA: Proof of Authority
    - Clique
    - Aura
    - Tendermint
 - POS: Proof of stake
    - Casper FFG (Under development)

I suggest that we have a chapter dedicated to ethereum networks. Additional things that we may include in that chapter would be how to setup these as private networks.

**Comment by aantonop** [comment]
@AyushyaChitransh Do you want to make a first attempt at adding a small amount of detail to differentiate Kovan and Rinkeby, especially how Geth and Parity support relate to it?

**Comment by AyushyaChitransh** [comment]
I've tried to add a "small" amount of detail to address the difference and requirement of different testnets.

**Comment by come-maiz** [comment]
Thank you @AyushyaChitransh !
