### ISSUE TITLE
Blockchain Governance from a Developer point of view

### ISSUE THREAD

**Issue by fjrojasgarcia** [ethereumbook/ethereumbook#336]
Through this issue I intend to highlight the importance that it can have for a developer to know what or who governs the evolution of the Ethereum protocol.

**Comment by lrettig** [comment]
Seconded. I see hardly any content that's been written, and in the TOC, on the topic of governance. If it were my book, I'd devote a chapter to this topic since I think it's enormously important -- important to understand how Ethereum came to be the way it is, important to understanding the processes that are happening right now, and most of all important for understanding how it will continue to evolve. Of course it's not terribly well defined at the moment and it's evolving, but it would be useful to add at least some information about how the informal governance process has worked up to now and how it may evolve going forward. I've been researching this topic, participating in governance myself, and I've begun writing on the topic.

Put another way: if I (and other contributors) were to author some content on the topic of governance, would @aantonop and @gavofyork consider including it?

**Comment by aantonop** [comment]
We'd love to include some content on governance. Add an outline and then
content to the "contrib" folder, with a couple PRs.

Can't promise it will make it into the first edition, as we are a month
away from closing that, but it can easily make it into the second edition
and be the basis of other improvements and contributions.

Let's get the ball rolling!

**Comment by fjrojasgarcia** [comment]
Thanks for support the proposal.

**Comment by lrettig** [comment]
I like deadlines. Deadlines are good. Hold my drink :)

Seriously though, governance is an important topic and it belongs in the first edition if at all possible. If you think there's a chance of making that deadline, I'll write this. (If not, given that Ethereum governance is such a moving target and there's less time pressure, I'd instead be inclined to wait a few months and see what changes).

I'll start working on this.

**Comment by SylTi** [comment]
> to know what or who governs the evolution of the Ethereum protocol.

If you wanted to troll a little bit you could resume the governance model to "PoV": Proof of Vitalik.

More seriously I think the governance model has some pretty big issues: 
Important peoples get bailed out, people that don't matter don't.

The first Parity hack got some people funds stolen before the white hat group could secure them, but there is only a recovery proposal for the second hack, the one where Parity got there own funds locked.

Also using a voting mechanism that allows Parity to vote with the Ethers locked inside the contract is sketchy at best. https://www.etherchain.org/coinvote/poll/35


Good luck in writing this section, it's not gonna be easy to stay neutral 😄

**Comment by lrettig** [comment]
> it's not gonna be easy to stay neutral

I hear you, but I disagree. A chapter on governance should attempt to describe _how things work today_ rather than _how they should work_, which is subjective and normative. It's pretty clear how things work today--not to say that they're perfect.

Here's a rough sketch of an outline for such a chapter:

- What is governance? Define it and tie it back to the "real world"
  - Coordination problems
  - Game theory
  - "On chain" / "tightly-coupled" governance versus "off-chain" / "loosely coupled"
- How does the Ethereum governance process work today?
  - Compare to other projects: Bitcoin, Tezos, Dfinity, DPos systems e.g. Lisk, Eos
  - The EIP process
  - The All Core Devs call
  - Implementations
  - The role of users, miners, app developers, etc.
  - Forks: how they happen, what they mean, associated challenges
- Community and consensus
  - Polls and knowing how the community feels
  - The challenges of doing this today
- Governance in the future
  - Ongoing proposals/initiatives for improving the process

**Comment by fjrojasgarcia** [comment]
[Notes on Blockchain Governance](https://vitalik.ca/general/2017/12/17/voting.html) - Vitalik Buterin's website

**Comment by lrettig** [comment]
Yes, I'm aware of that article, and I've borrowed some terms and ideas from it. Thanks for the link.

**Comment by lrettig** [comment]
This is a work in progress at https://github.com/ethereumbook/ethereumbook/compare/develop...lrettig:governance. Normally I would file a work-in-progress PR to track the progress, not sure if that's how you like to do things here, so I haven't yet.
