### ISSUE TITLE
Review, complete and edit section on Oracles

### ISSUE THREAD

**Issue by aantonop** [ethereumbook/ethereumbook#414]
The contrib/oracles.asciidoc section has some great content. It will be added to the first edition. 

Please:
* Review
* Comment
* Add content
* Fix issues
* Edit grammar, syntax, typos
* Suggest diagrams

Let's get it to final!

**Comment by Nideesh1** [comment]
Hi Andreas, here's a diagram for Oraclize for the reader to visualize the process. Will go through the oracles file further
![oraclize](https://user-images.githubusercontent.com/14232287/38486141-fdbe1f32-3b90-11e8-851d-d0f12e1ea995.png)

**Comment by timnugent** [comment]
I think this is a touch simplistic and could benefit from emphasising which aspects of the process occur on-chain, and which are off-chain. Attaching the BlockOne IQ architectural schema, which implements the same request-response pattern as Oraclize (major difference is that "TR Pricing APIs" in this would be placed outside the "TR Backend" panel for Oraclize, as Oraclize use web-based rather than internal APIs). I think any schematic image should be product/vendor agnostic though. 

![oracle](https://user-images.githubusercontent.com/1824707/38505368-ea0965a4-3c0e-11e8-8aa3-7a89cb725752.png)

**Comment by Nideesh1** [comment]
@timnugent Yes, you're right. Gotcha thanks

**Comment by aantonop** [comment]
It seems I've duplicated this issue. See #444.
