### ISSUE TITLE
Review comments and edit: vyper.asciidoc

### ISSUE THREAD

**Issue by aantonop** [ethereumbook/ethereumbook#445]
The vyper section has been moved into main, ready for review, comments and edits

**Comment by chanan-sack** [comment]
took a look, it was a bit of a mess but with a recent PR it should be work in progress.

**Comment by ltfschoen** [comment]
I'll try to take a look at this tomorrow. I just spent the last few days going through Vyper in depth. I'd like to show how  I compiled a simple contract, used the latest Web3.py to deploy it to a Geth Node or the Truffle Develop built-in blockchain, have the transaction mined, and with contract address obtained from the deployment transaction receipt show how to call its contract methods

**Comment by tpmccallum** [comment]
I have committed about a dozen changes, this is coming along nicely. When I started the bones of this chapter there were a lot of loose ends. The development of Vyper has been consistent so it is now just a matter of working through the TODOs in the asciidoc. It would be great to have more code examples. The suggestion on walking through the whole coding process, including compiling and deploying a contract is a great one. Perhaps we could use or modify on of the contracts provided at https://vyper.online for consistency (it is not obvious, but clicking on the “Open in editor” link at Vyper online reveals a bunch of pre written Vyper contracts)

**Comment by ltfschoen** [comment]
Here is the code I wrote and instructions on how to deploy a Vyper contract using either Geth Node or Truffe Develop  https://github.com/ltfschoen/vyper-test

**Comment by tpmccallum** [comment]
Hi @aantonop 
I have completed all of the many TODOs which I created at the outset. 
A new PR is available https://github.com/ethereumbook/ethereumbook/pull/582
The Vyper developers have been super helpful with this chapter, what a great community!
I will continue to keep an eye on upcoming developments, tests and documentation and keep up the writing, as the Vyper development inevitably continues on.
Kind regards
Tim

**Comment by tpmccallum** [comment]
@gavofyork I see that the tech review is coming along nicely. Apologies for not getting my Vyper chapter TODOs done before the freeze, I was not aware that the freeze was coming :(

This pull request < https://github.com/ethereumbook/ethereumbook/pull/582 > wraps up all of the TODOs (added since I started the Vyper chapter). This PR also adds continuity to the chapter. What would be the best way to integrate the changes from the above pull request? I appreciate that there is a workflow; just want to give my best to the book.

Kind regards
Tim
