### ISSUE TITLE
clients : a few issues

### ISSUE THREAD

**Issue by SylTi** [ethereumbook/ethereumbook#487]
Hey @aantonop , I found a few issues concerning the clients.asciidoc file

We must be very careful here when describing ethereum full node: 
a fast sync node does not validate the state after every block like a bitcoin pruned node would do, it only starts validating everything for something like the last 1000 blocks before the current state.
This means that fast sync nodes require some kind of level of trust which is not the case with a pruned bitcoin node. The distinction should be clear.

I'm not sure about the minimum requirement for running a node: 
last week I tried to sync Geth in fast mode, I couldn't even catch up using my dev laptop (i7, 16gb ram) because the i/o are just too much for a hdd

The amount of space required is also probably wrong: I couldn't completely sync the chain and I'm already over 64gb

**Comment by pyskell** [comment]
This issue is also compounded by a few variables:

1. Level of pruning, on a fully pruned parity node for example it's like <30 GB
1. Client, geth tends to use ~50% more disk space than parity. Other clients likely use different amounts as well

I think the existing recommendation in `clients.asciidoc` of checking 3rd party sources (which tend to use geth) is a good one as the chain size is always changing as it is.
