### ISSUE TITLE
Ethereum Recovery Proposal

### ISSUE THREAD

**Issue by SylTi** [ethereumbook/ethereumbook#506]
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-867.md

I think this should be discussed in the book, mainly because it is extremely controversial and kind of break the whole "Code is Law" paradigm. Opinions anyone? @aantonop

**Comment by fjrojasgarcia** [comment]
Super interesting @SylTi 

_"Frozen fund recovery proposals are almost never successful due to the relatively ad-hoc nature of such requests and the subjectivity that is often required to evaluate the merits. This EIP attempts to remove these barriers by providing both a standardized format for fund recovery EIPs and an objective standard by which to measure future proposals."_

**Comment by lrettig** [comment]
Agree that this (and http://eips.ethereum.org/EIPS/eip-999) are pretty important candidates for inclusion. Happy to summarize and/or contribute a write-up in the context of the governance topic (cf. #336).
