### ISSUE TITLE
Privacy on ethereum

### ISSUE THREAD

**Issue by fjrojasgarcia** [ethereumbook/ethereumbook#85]
I think Privacy on ethereum could be an important aspect to be cover by the book.

Thre are already several projects trying to implement privacy on ethereum, most notably Zcash-on-ethereum (ZoE), Hawk and the later Zcoin.

**Comment by QwQiao** [comment]
Agreed. The book could dedicate a section on zkSNARKs that went live with Byzantium.

**Comment by fjrojasgarcia** [comment]
ZK-SNARKs have a newer, shinier cousin: **ZK-STARKs**. With the T standing for “transparent”, ZK-STARKs resolve one of the primary weaknesses of ZK-SNARKs, its reliance on a “trusted setup”. 

https://vitalik.ca/general/2017/11/09/starks_part_1.html

**Comment by swasilyev** [comment]
> ZK-SNARKs have a newer, shinier cousin: ZK-STARKs. With the T standing for “transparent”, ZK-STARKs resolve one of the primary weaknesses of ZK-SNARKs, its reliance on a “trusted setup”.

Unfortunately that is not perfectly true. Though STARKS solve trusted setup problem, as some other nearly-practical solutions, see the list [https://zkp.science], I don’t think they are practical for Ethereum, at least until sharding/TrueBit/etc. Trusted setup is paid by SNARKS for constant-size proofs, and this price may appear inevitable, as I fail imagine prooving linear computation in constant time. Anyway, since Metropolis, that made them practical, we haven’t seen any reasonable applications, and STARKS can take even more time for adoption.

Regarding book content, the subject is complex, explanation to the depth where it becomes practical for non-specialist would take much space and may feel frightening to vast audience. More feasible may be a brief description of ideas behind the related Metropolis changes, and the possibilities that it created. The hard problem is the selection of topics as we  have no prooven approaches at the moment. It should be at least some primitives from “classical” cryptography, like Pedersen commitments, ring signatures, etc and at least SNARKS from zk-zoo, but it’s hard to which limits.

It’s all too opinionated for a single person at the moment, but if we can make it a collective effort I would be happy to elaborate.

**Comment by jeamick** [comment]
Hello there , for privacy on Ethereum we can talk about Multi party  computation with reference to the Enigma Project  : https://github.com/enigmampc
