### ISSUE TITLE
Specify why one can't recreate dao contract on Local Blockchain Simulation 

### ISSUE THREAD

**Issue by srghma** [ethereumbook/ethereumbook#913]
There is a sentence re Local Blockchain Simulation 

https://github.com/ethereumbook/ethereumbook/blob/develop/03clients.asciidoc

```
You can’t recreate some of the public contracts and their addresses to test some scenarios (e.g., the DAO contract).
```

Could you specify why?

Why it's not possible to reproduce DAO contract issue with enough computational power?

**Comment by FantasticKey4** [comment]
Test

**Comment by adrianmcli** [comment]
It's actually possible to fork off the main chain with Ganache. Paging @davidmurdoch and @nicholasjpaterno.

**Comment by davidmurdoch** [comment]
Only one of the disadvantages of using Ganache are currently true:

- Having no other users means that it doesn’t behave the same as a public blockchain. There’s no competition for transaction space or sequencing of transactions.
  - you are able to randomly submit transactions to ganache and it will order them by price and nonce. It doesn't have all of the nuances of transaction prioritization that a public geth miner might, but it gets you close.
- No miners other than you means that mining is more predictable; therefore, you can’t test some scenarios that occur on a public blockchain.
  - *This one is accurate*. I'm very interested to understand more about useful testing scenarios due to competing miners (is it just reorgs?).
- Having no other contracts means you have to deploy everything that you want to test, including dependencies and contract libraries.
  - you can persist your chain state to a directory with the `--db` flag (`db_path` option when using `ganache-core` directly), so you only need to deploy these contracts and libraries once, and with forking (see next comment) you don't have to deploy at all.
- You can’t recreate some of the public contracts and their addresses to test some scenarios (e.g., the DAO contract).
  - Ganache's forking mode enables forking off of testnets and mainnet at any previous block number without having to sync any state up front (this feature requires Internet access). Only the state that contracts and transactions on your private fork need to interact with will be requested from the original chain. Combined with unlocking any address, you can simulate any transaction you'd like (note: generated hashes will not be accurate due to not being able to actually sign the transactions with real private keys)
