### ISSUE TITLE
Hiring a Github Editor to manage this repo

### ISSUE THREAD

**Issue by aantonop** [ethereumbook/ethereumbook#921]
I would like to get a second print or second edition of the book released by Q2/Q3'2020. 

Unfortunately, I cannot focus time on processing all the PRs and Issues to get it done. Many of the examples are out of date and don't compile or work properly. They all need to be updated. Many have already been "fixed" with PRs, but all need to be tested and improved.

I am looking to hire a part-time editor, someone who is willing to put in 30-40 hours of work over the next 3 months to clear out all the outstanding issues, PRs and test all the examples in the book. At the end of it, we will release a new edition or print of the book. The Github editor will be given appropriate attribution in the preface. 

Please reply to this issue if you are interested and provide some supporting information as to why I should select you to do this. Also, please post your hourly rate in your reply. Payment will be made in USD, BTC or ETH. US Labor laws apply: I will need tax documentation and cannot hire people from sanctioned countries, but otherwise your location does not matter.

**Comment by Christofon** [comment]
Hi Andreas!

I'm Chris from Vienna, Austria. Been involved with crypto since 2016 and an enthusiastic advocate. That's why I would love to help you with this and thereby actively contribute to the education and onboarding of developers. Besides that, I as a student appreciate every opportunity to earn some extra crypto. :)
Hourly rate of $20 would be nice 

When it comes to technical knowledge to efficiently work on this task, I definitely feel confident. Not least because of your book.

**Comment by tryjude** [comment]
Hi Andreas,

I'm from Canada but I'll be spending time in Portugal in March and April on a little bit of a sabbatical. I'll have extra free time during this period to focus on the book and that was actually already my plan even before I saw your tweet. I have a hardcopy of Mastering Ethereum and will be taking it with me during this time away.

I've been mining Ethereum since 2017 and dabbling here and there in the technical details. I'm a software developer by trade although I admit I am no expert in Solidity (yet).

I have never been an editor per se but I believe I have excellent proofreading skills. I am a stickler for formatting and always give attention to detail when it comes to the written word.

It's tricky to say what rate I would need... perhaps $22.50 USD per hour? Give or take?

I don't have much to show you in terms of pull requests or Github issues but I am very familiar with Git and Github. I am totally comfortable with Linux and the command-line too. 

Thanks for your consideration.

**Comment by 0xmountaintop** [comment]
Hi Andreas,

I am HAOYU from China,

PR:

+ https://github.com/ethereum/go-ethereum/pull/17571
+ https://github.com/vyperlang/vyper/pull/1046

I co-design https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2266.md , a fair atomic swap protocol. 

I have a new paper on ETH2.0 sharding, but the result is not out yet, so I am not sure whether it can get accepted and I'd better don't provide further detail.

Expected rate is $20.

Always excited to participate, thx!

**Comment by v1thesource** [comment]
Hi Andreas,

I'm Alex from London, though I'm currently based in Zurich. I'm a native English speaker and recently completed my Ph.D. thesis (https://github.com/v1thesource/PhD-Thesis), so I have ample experience in writing and editing a large technical document. I've run an Ethereum full node in the past (mostly for learning/curiosity) and have the programming competencies to properly test out the examples in the book. 

Rate: $30/hr. Preferably in BTC or ETH.

Thanks for your consideration.

**Comment by iquidus** [comment]
Hi Andreas,

I'm Luke, a core developer of Ubiq. I've been an open source dev for many years and would be more than happy to volunteer time to this. You've contributed a tremendous amount to this space and books like this are an invaluable resource for new developers. As such, my hourly rate would be $0.

I have ample experience running nodes, writing block explorers, writing and deploying contracts/tokens, and Github may as well be my second home.

Here are some relevant examples, but I'd be happy to provide more specific ones:

* https://github.com/ethereumclassic/ECIPs/issues/253#issuecomment-569340722
* https://github.com/ubiq/UIPs/issues/6
* https://github.com/iquidus/explorer/pull/23

Thank you for your consideration.

**Comment by ghost** [comment]
Hi Andreas,
I'm Moazaad, and I would love to volunteer my free time to help you on this project with no cost. Why you should hire me for this? This is because we are going to start a special relation here. Let's make decentralization speed up!

**Comment by tomw1808** [comment]
Hi,
I'm Thomas, I did one of the first video courses on Ethereum Development back in 2016 when AlethZero and Solidity 0.3 was in. I recorded then a couple more courses over the past years, about truffle, geth, pantheon/besu, web3@0.20, web3@1.0.0, the list goes on. I worked for the blockchain training alliance as advisor for their Ethereum certification program. I also published a book on Ethereum Blockchain Development and also a training guide covering pretty much anything one can ask about (Ethereum) Blockchain development. I still do consulting and training work in that space.

A friend send me the link to your repo. I would give up my efforts to update my own book and work on this one instead without thinking twice.

Let me know and we'll figure out the details.

Thomas

**Comment by us3r01** [comment]
Hi, I'm from Mexico. 

I'm creating an Ethereum and Maker Dao course for the startup Lumit incubated at Blockchain at Berkeley. I have a blockchain certification issued by Consensys . My knowledge about Ethereum is up to date. 

Attached you my Linkedin if you would like to connect. 

https://www.linkedin.com/in/398169174/

My hourly rate is $20 USD. 

Best Regards!

**Comment by CallMeGwei** [comment]
I've been in the blockchain space a while, transitioning from the writing/philosophical side of the space to the developer side over the past year and a half.

I've been "certified" as an Ethereum dev by B9Lab and was also one of the inaugural students in Truffle University last year.

I'm currently about 33.5% of the way through Mastering Ethereum - and have had a few small quibbles here and there with content. This request of yours is something like a call to action - I had been wanting to make some contributions to this repo anyway.

I'd be glad to get the PRs all caught up and contribute some additional prose and code QA.

That said, I think 40 hours may be under-estimating the work-load a bit, assuming more PRs will trickle in.

If I were going to ask for payment - it would most certainly be in ether, but I'd rather do it in exchange for brand recognition - a CallMeGwei logo and/or URL someplace in the book would be profoundly satisfying.

I plan on being in this space in perpetuity, so I wouldn't be treating this as a one-off side gig.

**Comment by safetyth1rd** [comment]
Hi my name is Danger Zhang and I'm the guy on twitter who prodded you to create this request =) 

I'm a professional technical content writer with writing and editing experience for technical publications. I recently contributed major sections to and edited multiple chapters of ["Fundamentals of Smart Contract Security" by Quantstamp](https://www.amazon.com/Fundamentals-Smart-Contract-Security-Richard/dp/194944936X). This  editing was primarily in Overleaf(Latex editor) but i'm also familar with Github. I've been writing about Ethereum for 2 years. 

I'm already 70% of the way through Mastering Ethereum and have been documenting my progress on Twitter using #MasteringEthereum. Having worked through most of the technical exercises and also taken thorough notes, I'm familiar with which places are out of date as well as which specific technical fixes are needed. 

I have a degree in Computer Engineering from the University of Maryland, so I have the technical understanding to properly address all topics in the book. 

I would ask for a rate of $30/hr, which is below my regular rate as this project is good for the community. Since I'm already familiar with the book and many of the issues involved, I should be able to work fairly efficiently on this.

**Comment by adrianmcli** [comment]
Hi @aantonop from the Truffle team!

I'm the director of frontend engineering and developer relations at Truffle.

We want to lend our official support in editing and correcting mistakes relating to Truffle usage in the book. We'll make sure that the book is as accurate and as up-to-date as it needs to be. Of course, we will be doing all this for free in the spirit of open-source.

As a previous contributor to this book, I hope that we can move the Ethereum ecosystem forward together. Both myself and @nicholasjpaterno will be actively helping out whenever possible.

Feel free to reach out personally to me if you'd like to work together even more closely (I use the same handle on Twitter, LinkedIn, etc.).

**Comment by aantonop** [comment]
I have engaged @safetyth1rd (who was one of the first to start working on revising these examples) to complete the work. In addition, @wbnns is doing the editorial and repository work he has always done.

Thank you @safetyth1rd and thank you @wbnns !

With this help I expect we will get the second print up and done soon enough. More good news to follow!

**Comment by adrianmcli** [comment]
This is awesome! @safetyth1rd and @wbnns don't hesitate to reach out to me personally if you would like any help from the Truffle team! Feel free to tag me in any PRs that are relevant.

**Comment by aantonop** [comment]
@adrianmcli  @nicholasjpaterno Very much appreciate your help with any and all examples that mention truffle or any truffle-related parts of the book that need corrections. Please submit PRs! We want to get to a second print before the end of February

**Comment by wbnns** [comment]
@adrianmcli @nicholasjpaterno Thanks so much. I sent you all an email.
